/**
 * E2E Test Client Helper
 *
 * Provides access to the generated client for tests.
 * The client is generated by the preload script before tests run.
 *
 * NOTE: Uses static imports for proper TypeScript type inference.
 * Run `bun test tests/e2e/ --preload ./tests/e2e/preload.ts` to ensure
 * generated files exist before tests run.
 */

// Static imports from generated directory for proper type inference
// These files are created by preload.ts before tests run
import { SurrealClient } from './generated/client';

// Re-export client class and types
export { SurrealClient };
export * from './generated/models';

// Factory function to create a new client instance
export function createTestClient(): SurrealClient {
  return new SurrealClient();
}

// Test database configuration
export const testConfig = {
  url: 'http://127.0.0.1:8000',
  namespace: 'main',
  database: 'main',
  auth: {
    username: 'root',
    password: 'root',
  },
};

// Helper to clean up test tables
export async function cleanupTables(client: SurrealClient): Promise<void> {
  const surreal = client.getSurreal();
  if (surreal) {
    try {
      await surreal.query('REMOVE TABLE IF EXISTS user;');
      await surreal.query('REMOVE TABLE IF EXISTS profile;');
      await surreal.query('REMOVE TABLE IF EXISTS post;');
      await surreal.query('REMOVE TABLE IF EXISTS tag;');
    } catch {
      // Ignore errors
    }
  }
}
