/**
 * E2E Test Client Helper
 *
 * Provides access to the generated client for tests.
 * The client is generated by the preload script before tests run.
 *
 * NOTE: Uses static imports for proper TypeScript type inference.
 * Run `bun test tests/e2e/ --preload ./tests/e2e/preload.ts` to ensure
 * generated files exist before tests run.
 */

// Static imports from generated directory for proper type inference
// These files are created by preload.ts before tests run
import { CerialClient } from './generated/client';

// Re-export client class and types
export { CerialClient };
export * from './generated/models';

// Factory function to create a new client instance
export function createTestClient(): CerialClient {
  return new CerialClient();
}

// Test database configuration
export const testConfig = {
  url: 'http://127.0.0.1:8000',
  namespace: 'main',
  database: 'main',
  auth: {
    username: 'root',
    password: 'root',
  },
};

// Tables used by the root-level E2E test files
const ROOT_TABLES = ['user', 'profile', 'post', 'tag', 'array_decorator_test'];

// Helper to clean up test tables (REMOVE + migrate — heavy, use in beforeAll)
export async function cleanupTables(client: CerialClient): Promise<void> {
  const surreal = client.getSurreal();
  if (surreal) {
    for (const table of ROOT_TABLES) {
      try {
        await surreal.query(`REMOVE TABLE IF EXISTS ${table};`);
      } catch {
        // Ignore errors
      }
    }
  }
  // Reset migration tracking so migrate() re-runs DEFINE statements
  client.resetMigrationState();
  // Re-run migrations to recreate tables with correct schema
  await client.migrate();
}

/**
 * Truncate root tables by deleting all rows.
 * Lightweight alternative to cleanupTables — preserves schema, just clears data.
 * Use in `beforeEach` for fast per-test cleanup.
 */
export async function truncateTables(client: CerialClient): Promise<void> {
  const surreal = client.getSurreal();
  if (!surreal) return;

  for (const table of ROOT_TABLES) {
    try {
      await surreal.query(`DELETE FROM ${table};`);
    } catch {
      // Ignore errors - table may not exist yet
    }
  }
}
